name: Test and Package

on: 
  workflow_call:
    inputs:
      upload:
        required: false
        type: boolean
        default: false

  push:
    branches:
      - "**"

jobs:
  test-and-package:
    name: Test and Package
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v6

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Setup Build Tools 
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build

    - name: Download Dependencies
      run: pip install -e ".[test]"

    - name: Type Check
      run: mypy src

    - name: PyTest
      run: pytest

    - name: Shell Test
      run: shell_tests/shell_test.sh

    - name: Package
      run: python -m build

    - name: Upload Dist
      if: ${{ inputs.upload }}
      uses: actions/upload-artifact@v7
      with:
        name: dist
        path: dist/
